import React from "react"
import { IconHexagon } from "./IconHexagon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconHexagon,
  "https://www.figma.com/design/q0sGYgf7vTgsuoM979pMgw/Simple-Design-System--Community-?node-id=4039%3A12359",
  {
    props: {},
    example: (props) => <IconHexagon />,
  },
)
