import React from "react"
import { IconArrowUpRight } from "./IconArrowUpRight"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconArrowUpRight,
  "https://www.figma.com/design/q0sGYgf7vTgsuoM979pMgw/Simple-Design-System--Community-?node-id=4039%3A12450",
  {
    props: {},
    example: (props) => <IconArrowUpRight />,
  },
)
